ASPCore/Controllers/AuthorController.cs
using ASPCore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ASPCore.Controllers
{
	public class AuthorController : Controller
	{
		private readonly FilmDbContext _context;

		public AuthorController(FilmDbContext context)
		{
			_context = context;
		}

        // Index action to view all authors
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var authorsWithFilms = await _context.Authors.Include(a => a.Films).ToListAsync();
            return View(authorsWithFilms);
        }

        // Create action (GET)
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
		{
			return View();
		}

		// Create action (POST)
		[HttpPost]
		[ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(Author author)
		{
			if (ModelState.IsValid)
			{
				Author newAuthor = new Author
				{
					Name = author.Name,
					Surname = author.Surname,
					DateOfBirth = author.DateOfBirth,
				};

				_context.Authors.Add(newAuthor);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}

			// Log ModelState errors
			foreach (var modelState in ModelState.Values)
			{
				foreach (var error in modelState.Errors)
				{
					Console.WriteLine($"ModelState Error: {error.ErrorMessage}");
				}
			}

			return View(author);
		}
		[HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Update(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var author = await _context.Authors.FindAsync(id);
			if (author == null)
			{
				return NotFound();
			}

			return View(author);
		}

		// Update action (POST)
		[HttpPost]
		[ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Update(int id, Author author)
		{
			if (id != author.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(author);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!AuthorExists(author.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			return View(author);
		}

		// Delete action (POST)
		[HttpPost]
		[ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
		{
			var author = await _context.Authors.FindAsync(id);
			_context.Authors.Remove(author);
			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		private bool AuthorExists(int id)
		{
			return _context.Authors.Any(e => e.Id == id);
		}

	}
}

ASPCore/Controllers/FilmController.cs
using ASPCore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace ASPCore.Controllers
{

	public class FilmController : Controller
	{
		private readonly FilmDbContext _context;

		public FilmController(FilmDbContext context)
		{
			_context = context;
		}
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
		{
            var films = await _context.Films
                .Include(f => f.Comments) // Include the Comments in the query
                .ToListAsync();

            var authors = await _context.Authors.ToDictionaryAsync(a => a.Id, a => a.Name);

            ViewBag.Authors = authors;

            return View(films);
        }
		[HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
		{
			ViewBag.Authors = new SelectList(_context.Authors, "Id", "Name");
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(FilmViewModel filmViewModel)
		{
			if (ModelState.IsValid)
			{
				var author = await _context.Authors.FindAsync(filmViewModel.AuthorId);
				if (author == null)
				{
					ModelState.AddModelError("", "Author not found");
					return View(filmViewModel);
				}

				string fileName = null;
				if (filmViewModel.Image != null)
				{
					fileName = Path.GetFileName(filmViewModel.Image.FileName);
					var filePath = Path.Combine("wwwroot/images", fileName);
					using (var fileStream = new FileStream(filePath, FileMode.Create))
					{
						await filmViewModel.Image.CopyToAsync(fileStream);
					}
				}

				Film newFilm = new Film
				{
					Name = filmViewModel.Name,
					AuthorId = filmViewModel.AuthorId,
					ReleaseDate = filmViewModel.ReleaseDate,
					Category = filmViewModel.Category,
					Description = filmViewModel.Description,
					ImagePath = fileName != null ? $"~/images/{fileName}" : null
				};

				if (author.Films == null)
				{
					author.Films = new List<Film>();
				}
				author.Films.Add(newFilm);

				_context.Films.Add(newFilm);
				_context.Authors.Update(author);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}

			// Log ModelState errors
			foreach (var modelState in ModelState.Values)
			{
				foreach (var error in modelState.Errors)
				{
					Console.WriteLine($"ModelState Error: {error.ErrorMessage}");
				}
			}

			return View(filmViewModel);
		}
		[HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Update(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var film = await _context.Films.FindAsync(id);
			if (film == null)
			{
				return NotFound();
			}

			return View(film);
		}

		// Update action (POST)
		[HttpPost]
		[ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Update(int id, Film film)
		{
			if (id != film.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(film);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!FilmExists(film.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			return View(film);
		}

		// Delete action (POST)
		[HttpPost]
		[ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
		{
			var film = await _context.Films.Include(f => f.Comments).FirstOrDefaultAsync(f => f.Id == id);
			if (film == null)
			{
				return NotFound();
			}

			_context.Films.Remove(film);
			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}
		private bool FilmExists(int id)
		{
			return _context.Films.Any(e => e.Id == id);
		}


	}
}

ASPCore/Controllers/RoleController.cs
using System.ComponentModel.DataAnnotations;
using ASPCore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ASPCore.Controllers
{
	public class RoleController : Controller
	{
        private RoleManager<IdentityRole> roleManager;
        private UserManager<AppUser> userManager;

        public RoleController(RoleManager<IdentityRole> roleMgr, UserManager<AppUser> userMrg)
        {
            roleManager = roleMgr;
            userManager = userMrg;
        }
        [Authorize(Roles = "Admin")]
        public ViewResult Index() => View(roleManager.Roles);

        private void Errors(IdentityResult result)
        {
            foreach (IdentityError error in result.Errors)
                ModelState.AddModelError("", error.Description);
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Create() => View();

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Required] string name)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result = await roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                    return RedirectToAction("Index");
                else
                    Errors(result);
            }
            return View(name);
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await roleManager.DeleteAsync(role);
                if (result.Succeeded)
                    return RedirectToAction("Index");
                else
                    Errors(result);
            }
            else
                ModelState.AddModelError("", "No role found");
            return View("Index", roleManager.Roles);
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Update(string id)
        {
            IdentityRole role = await roleManager.FindByIdAsync(id);
            List<AppUser> members = new List<AppUser>();
            List<AppUser> nonMembers = new List<AppUser>();
            foreach (AppUser user in userManager.Users)
            {
                var list = await userManager.IsInRoleAsync(user, role.Name) ? members : nonMembers;
                list.Add(user);
            }
            return View(new RoleEdit
            {
                Role = role,
                Members = members,
                NonMembers = nonMembers
            });
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Update(RoleModification model)
        {
            IdentityResult result;
            if (ModelState.IsValid)
            {
                foreach (string userId in model.AddIds ?? new string[] { })
                {
                    AppUser user = await userManager.FindByIdAsync(userId);
                    if (user != null)
                    {
                        result = await userManager.AddToRoleAsync(user, model.RoleName);
                        if (!result.Succeeded)
                            Errors(result);
                    }
                }
                foreach (string userId in model.DeleteIds ?? new string[] { })
                {
                    AppUser user = await userManager.FindByIdAsync(userId);
                    if (user != null)
                    {
                        result = await userManager.RemoveFromRoleAsync(user, model.RoleName);
                        if (!result.Succeeded)
                            Errors(result);
                    }
                }
            }

            if (ModelState.IsValid)
                return RedirectToAction(nameof(Index));
            else
                return await Update(model.RoleId);
        }
    }
}

ASPCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASPCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASPCore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASPCore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>*@
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
	                <ul class="navbar-nav flex-grow-1">
		                <li class="nav-item">
			                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
		                </li>
                        @if (User?.Identity?.IsAuthenticated ?? false)
                        {
	                        @if (User.IsInRole("Admin"))
                            {
	                            <li class="nav-item">
		                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin</a>
	                            </li>
	                            <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Author" asp-action="Index">Author</a>
	                            </li>
	                            <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Film" asp-action="Index">Film</a>
	                            </li>
	                            <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Role</a>
	                            </li>

                            }
                        }
                    </ul>
	                <div class="navbar-right">
		                @if (User?.Identity?.IsAuthenticated ?? false)
		                {
                            <a>Welcome, @User.Identity.Name</a>
                            <a asp-controller="Account" asp-action="Logout" class="btn btn-danger">Logout</a>
                        }
                        else
                        {
	                        <a class="btn btn-primary" asp-controller="Account" asp-action="Login" asp-route-ReturnUrl="@Context.Request.Path">Login</a>
                            <a class="btn btn-secondary" asp-controller="Account" asp-action="Register" asp-route-ReturnUrl="@Context.Request.Path">Register</a>
                        }
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>